
package com.thy.loyalty.ms.ws.redemption;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AwardOperationsService", targetNamespace = "http://redemption.ws.ms.thy.com/", wsdlLocation = "/META-INF/wsdl/AwardOperationsService/AwardOperationsService.wsdl")
public class AwardOperationsService_Service
    extends Service
{

    private final static URL AWARDOPERATIONSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.thy.loyalty.ms.ws.redemption.AwardOperationsService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.thy.loyalty.ms.ws.redemption.AwardOperationsService_Service.class.getResource(".");
            url = new URL(baseUrl, "/META-INF/wsdl/AwardOperationsService/AwardOperationsService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/META-INF/wsdl/AwardOperationsService/AwardOperationsService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AWARDOPERATIONSSERVICE_WSDL_LOCATION = url;
    }

    public AwardOperationsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AwardOperationsService_Service() {
        super(AWARDOPERATIONSSERVICE_WSDL_LOCATION, new QName("http://redemption.ws.ms.thy.com/", "AwardOperationsService"));
    }

    /**
     * 
     * @return
     *     returns AwardOperationsService
     */
    @WebEndpoint(name = "AwardOperationsServicePort")
    public AwardOperationsService getAwardOperationsServicePort() {
        return super.getPort(new QName("http://redemption.ws.ms.thy.com/", "AwardOperationsServicePort"), AwardOperationsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AwardOperationsService
     */
    @WebEndpoint(name = "AwardOperationsServicePort")
    public AwardOperationsService getAwardOperationsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://redemption.ws.ms.thy.com/", "AwardOperationsServicePort"), AwardOperationsService.class, features);
    }

}
