
package com.thy.loyalty.ms.ws.redemption;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.thy.loyalty.ws.requestheader.RequestHeader;
import com.thy.loyalty.ws.responseheader.ResponseHeader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AwardOperationsService", targetNamespace = "http://redemption.ws.ms.thy.com/")
@XmlSeeAlso({
    com.thy.loyalty.ws.requestheader.ObjectFactory.class,
    com.thy.loyalty.ms.ws.redemption.ObjectFactory.class,
    com.thy.loyalty.ws.responseheader.ObjectFactory.class
})
public interface AwardOperationsService {


    /**
     * 
     * @param responseHeader
     * @param nonAirAwardReversalDetail
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.redemption.NonAirAwardReversalResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nonAirAwardReversal", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirAwardReversal")
    @ResponseWrapper(localName = "nonAirAwardReversalResponse", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirAwardReversalResponse")
    public NonAirAwardReversalResult nonAirAwardReversal(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "nonAirAwardReversalDetail", targetNamespace = "")
        NonAirAwardReversalDetail nonAirAwardReversalDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param nonAirReissueAwardDetail
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.redemption.NonAirReissueAwardResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nonAirReissueAward", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirReissueAward")
    @ResponseWrapper(localName = "nonAirReissueAwardResponse", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirReissueAwardResponse")
    public NonAirReissueAwardResult nonAirReissueAward(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "nonAirReissueAwardDetail", targetNamespace = "")
        NonAirReissueAwardDetail nonAirReissueAwardDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param nonAirIssueAwardDetail
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.redemption.NonAirIssueAwardResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nonAirIssueAward", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirIssueAward")
    @ResponseWrapper(localName = "nonAirIssueAwardResponse", targetNamespace = "http://redemption.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.redemption.NonAirIssueAwardResponse")
    public NonAirIssueAwardResult nonAirIssueAward(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "nonAirIssueAwardDetail", targetNamespace = "")
        NonAirIssueAwardDetail nonAirIssueAwardDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

}
