
package com.thy.loyalty.ms.ws.common.w3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.thy.loyalty.ws.requestheader.RequestHeader;
import com.thy.loyalty.ws.responseheader.ResponseHeader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculateFlightMilesService", targetNamespace = "http://w3.common.ws.ms.thy.com/")
@XmlSeeAlso({
    com.thy.loyalty.ws.requestheader.ObjectFactory.class,
    com.thy.loyalty.ms.ws.common.w3.ObjectFactory.class,
    com.thy.loyalty.ws.responseheader.ObjectFactory.class
})
public interface CalculateFlightMilesService {


    /**
     * 
     * @param responseHeader
     * @param calculateFlightMilesDetail
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.common.w3.CalculateFlightMilesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateFlightMiles", targetNamespace = "http://w3.common.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.common.w3.CalculateFlightMiles")
    @ResponseWrapper(localName = "calculateFlightMilesResponse", targetNamespace = "http://w3.common.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.common.w3.CalculateFlightMilesResponse")
    public CalculateFlightMilesResult calculateFlightMiles(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "calculateFlightMilesDetail", targetNamespace = "")
        CalculateFlightMilesDetail calculateFlightMilesDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

}
