
package gtesb.bc1c2850;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BC1C2850Service", targetNamespace = "http://gtesb/BC1C2850/", wsdlLocation = "THY_OFFER_USE.WSDL")
public class BC1C2850Service
    extends Service
{

    private final static URL BC1C2850SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gtesb.bc1c2850.BC1C2850Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gtesb.bc1c2850.BC1C2850Service.class.getResource(".");
            url = new URL(baseUrl, "THY_OFFER_USE.WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'THY_OFFER_USE.WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BC1C2850SERVICE_WSDL_LOCATION = url;
    }

    public BC1C2850Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BC1C2850Service() {
        super(BC1C2850SERVICE_WSDL_LOCATION, new QName("http://gtesb/BC1C2850/", "BC1C2850Service"));
    }

    /**
     * 
     * @return
     *     returns BC1C2850PortType
     */
    @WebEndpoint(name = "BC1C2850SOAPPort")
    public BC1C2850PortType getBC1C2850SOAPPort() {
        return super.getPort(new QName("http://gtesb/BC1C2850/", "BC1C2850SOAPPort"), BC1C2850PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BC1C2850PortType
     */
    @WebEndpoint(name = "BC1C2850SOAPPort")
    public BC1C2850PortType getBC1C2850SOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gtesb/BC1C2850/", "BC1C2850SOAPPort"), BC1C2850PortType.class, features);
    }

}
