
package com.thy.loyalty.ms.ws.w3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.thy.loyalty.ws.requestheader.RequestHeader;
import com.thy.loyalty.ws.responseheader.ResponseHeader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MemberCredentialService", targetNamespace = "http://w3.ws.ms.thy.com/")
@XmlSeeAlso({
    com.thy.loyalty.ms.ws.w3.ObjectFactory.class,
    com.thy.loyalty.ws.requestheader.ObjectFactory.class,
    com.thy.loyalty.ws.responseheader.ObjectFactory.class
})
public interface MemberCredentialService {


    /**
     * 
     * @param responseHeader
     * @param memberLoginDetails
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.MemberLoginW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "memberLogin", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.MemberLogin")
    @ResponseWrapper(localName = "memberLoginResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.MemberLoginResponse")
    public MemberLoginW3Result memberLogin(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "memberLoginDetails", targetNamespace = "")
        MemberLoginDetails memberLoginDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isServiceUp", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsServiceUp")
    @ResponseWrapper(localName = "isServiceUpResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsServiceUpResponse")
    public String isServiceUp();

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param checkCredentialDetails
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.CheckCredentialW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkMemberCredentials", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckMemberCredentials")
    @ResponseWrapper(localName = "checkMemberCredentialsResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckMemberCredentialsResponse")
    public CheckCredentialW3Result checkMemberCredentials(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkCredentialDetails", targetNamespace = "")
        CheckCredentialDetails checkCredentialDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param checkCredentialDetails
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.CheckCredentialW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkMemberCredentialsForFG", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckMemberCredentialsForFG")
    @ResponseWrapper(localName = "checkMemberCredentialsForFGResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckMemberCredentialsForFGResponse")
    public CheckCredentialW3Result checkMemberCredentialsForFG(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkCredentialDetails", targetNamespace = "")
        CheckCredentialDetails checkCredentialDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param checkPinSecurityDetails
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.CheckCredentialW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPinSecurity", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPinSecurity")
    @ResponseWrapper(localName = "checkPinSecurityResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPinSecurityResponse")
    public CheckCredentialW3Result checkPinSecurity(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkPinSecurityDetails", targetNamespace = "")
        CheckPinSecurityDetails checkPinSecurityDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param checkPinSecurityForNewMemberDetails
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.CheckCredentialW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPinSecurityForNewMember", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPinSecurityForNewMember")
    @ResponseWrapper(localName = "checkPinSecurityForNewMemberResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPinSecurityForNewMemberResponse")
    public CheckCredentialW3Result checkPinSecurityForNewMember(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkPinSecurityForNewMemberDetails", targetNamespace = "")
        CheckPinSecurityForNewMemberDetails checkPinSecurityForNewMemberDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param findMemberByMobilePhoneDetails
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.CheckCredentialW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findMemberByMobilePhone", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.FindMemberByMobilePhone")
    @ResponseWrapper(localName = "findMemberByMobilePhoneResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.FindMemberByMobilePhoneResponse")
    public CheckCredentialW3Result findMemberByMobilePhone(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "findMemberByMobilePhoneDetails", targetNamespace = "")
        FindMemberByMobilePhoneDetails findMemberByMobilePhoneDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param checkCredentialDetails
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.MemberPinUpdateW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMemberPin", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.UpdateMemberPin")
    @ResponseWrapper(localName = "updateMemberPinResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.UpdateMemberPinResponse")
    public MemberPinUpdateW3Result updateMemberPin(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkCredentialDetails", targetNamespace = "")
        CheckCredentialDetails checkCredentialDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param checkCredentialDetails
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.MemberLoginW3Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPin2Reset", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPin2Reset")
    @ResponseWrapper(localName = "checkPin2ResetResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.CheckPin2ResetResponse")
    public MemberLoginW3Result checkPin2Reset(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "checkCredentialDetails", targetNamespace = "")
        CheckCredentialDetails checkCredentialDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param maxPinLengthDetails
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.MaxPinLengthResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPinRules", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetPinRules")
    @ResponseWrapper(localName = "getPinRulesResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetPinRulesResponse")
    public MaxPinLengthResult getPinRules(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "maxPinLengthDetails", targetNamespace = "")
        MaxPinLengthDetails maxPinLengthDetails,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param isMemberValidDetail
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.IsMemberValidResults
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isMemberValid", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsMemberValid")
    @ResponseWrapper(localName = "isMemberValidResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsMemberValidResponse")
    public IsMemberValidResults isMemberValid(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "isMemberValidDetail", targetNamespace = "")
        IsMemberValidDetail isMemberValidDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

}
