
package com.thy.loyalty.ms.ws.w3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.thy.loyalty.ws.requestheader.RequestHeader;
import com.thy.loyalty.ws.responseheader.ResponseHeader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MemberDetailsService", targetNamespace = "http://w3.ws.ms.thy.com/")
@XmlSeeAlso({
    com.thy.loyalty.ms.ws.w3.ObjectFactory.class,
    com.thy.loyalty.ws.requestheader.ObjectFactory.class,
    com.thy.loyalty.ws.responseheader.ObjectFactory.class
})
public interface MemberDetailsService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isServiceUp", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsServiceUp")
    @ResponseWrapper(localName = "isServiceUpResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.IsServiceUpResponse")
    public String isServiceUp();

    /**
     * 
     * @param getMemberDetailsDetail
     * @param responseHeader
     * @param requestHeader
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.GetMemberDetailsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMemberDetails", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetMemberDetails")
    @ResponseWrapper(localName = "getMemberDetailsResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetMemberDetailsResponse")
    public GetMemberDetailsResult getMemberDetails(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "getMemberDetailsDetail", targetNamespace = "")
        GetMemberDetailsDetail getMemberDetailsDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

    /**
     * 
     * @param responseHeader
     * @param requestHeader
     * @param getMultiMemberDetailsDetail
     * @return
     *     returns com.thy.entrychannel.ms.ws.w3.GetMultiMemberDetailsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultiMemberDetails", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetMultiMemberDetails")
    @ResponseWrapper(localName = "getMultiMemberDetailsResponse", targetNamespace = "http://w3.ws.ms.thy.com/", className = "com.thy.entrychannel.ms.ws.w3.GetMultiMemberDetailsResponse")
    public GetMultiMemberDetailsResult getMultiMemberDetails(
        @WebParam(name = "requestHeader", targetNamespace = "")
        RequestHeader requestHeader,
        @WebParam(name = "getMultiMemberDetailsDetail", targetNamespace = "")
        GetMultiMemberDetailsDetail getMultiMemberDetailsDetail,
        @WebParam(name = "responseHeader", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ResponseHeader> responseHeader);

}
