
package com.thy.loyalty.ms.ws.w3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "W3MemberCredentialService", targetNamespace = "http://w3.ws.ms.thy.com/", wsdlLocation = "W3MemberCredentialService.wsdl")
public class W3MemberCredentialService
    extends Service
{

    private final static URL W3MEMBERCREDENTIALSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.thy.loyalty.ms.ws.w3.W3MemberCredentialService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.thy.loyalty.ms.ws.w3.W3MemberCredentialService.class.getResource(".");
            url = new URL(baseUrl, "W3MemberCredentialService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'W3MemberCredentialService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        W3MEMBERCREDENTIALSERVICE_WSDL_LOCATION = url;
    }

    public W3MemberCredentialService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public W3MemberCredentialService() {
        super(W3MEMBERCREDENTIALSERVICE_WSDL_LOCATION, new QName("http://w3.ws.ms.thy.com/", "W3MemberCredentialService"));
    }

    /**
     * 
     * @return
     *     returns MemberCredentialService
     */
    @WebEndpoint(name = "MemberCredentialServicePort")
    public MemberCredentialService getMemberCredentialServicePort() {
        return super.getPort(new QName("http://w3.ws.ms.thy.com/", "MemberCredentialServicePort"), MemberCredentialService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberCredentialService
     */
    @WebEndpoint(name = "MemberCredentialServicePort")
    public MemberCredentialService getMemberCredentialServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://w3.ws.ms.thy.com/", "MemberCredentialServicePort"), MemberCredentialService.class, features);
    }

}
